### ISSUE TITLE
Extremely high CPU usage

### ISSUE THREAD

**Issue by Nilzor** [sujoyu/plantuml-previewer#3]
The deployment at http://sujoyu.github.io/plantuml-previewer/ uses a _lot_ of CPU. Not sure if easily fixable or an intrinsic part of the solution

![image](https://user-images.githubusercontent.com/990654/39519404-ed7dc11c-4e06-11e8-91e3-bb15a69fd222.png)

Tested on Chrome 65 and Firefox 59.0.2 on Ubuntu 16

**Comment by sujoyu** [comment]
d7138613507aa2bbd040afcfd3ad0b8c28347b17
High CPU usage bug is fixed by this commit.
Thanks for the report!
